### ISSUE TITLE
Assertion fail in lang.c

### ISSUE THREAD

**Issue by docteurdoom** [tevador/polyseed#7]
Native builds of the Feather wallet (any version) fail to run because of the following reason:

bash5.1$ feather
feather: /var/tmp/portage/dev-libs/polyseed-1.0.0/work/polyseed-1.0.0/src/lang.c:256: polyseed_lang_check: Assertion `!strcmp(" ", separator)' failed.
Aborted 

Possible solution is to comment out the line 256 in src/lang.c

OS: Gentoo Linux x86_64 glibc. Default installation in VirtualBox.

**Comment by tevador** [comment]
> Possible solution is to comment out the line 256 in src/lang.c

That assert is there for a reason. If the separator does not normalize to a space, polyseed will fail to parse the mnemonic phrase.

A possible reason for the error that the dependency you are injecting for `u8_nfkd` doesn't work. Can you check that the string `u8"\u3000"` decomposes to `" "` with your dependency?

**Comment by tevador** [comment]
Whatever function you are passing to `polyseed_dependency.u8_nfkd` when calling `polyseed_inject`, call it with the (first) argument `u8"\u3000"` and report the results. Note that this function is not part of polyseed, so if it doesn't decompose correctly, it's either a bug in your code or some 3rd party depdendency you are using.

**Comment by tobtoht** [comment]
This was caused by `boost::locale::normalize`, which Feather injects for `u8_nfkd` and does not properly decompose the idiographic space (`\u3000`) to a 'normal' space (`\u0020`) in some circumstances, despite using `norm_nfkd`. I was able to reproduce this issue on Gentoo Linux with the musl overlay, but did not have time to work out the precise cause.

To avoid adding an additional dependency, I changed Feather to use [Qt's unicode normalization](https://doc.qt.io/qt-6/qstring.html#normalized), which appears to be more robust. Another option was to use [ICU](https://unicode-org.github.io/icu/userguide/icu4c/).
